# Example Configuration File
# Copy this file to courses.yaml and modify as needed

# Global Settings
settings:
  headless: false  # Run browser in headless mode
  screenshot_dir: "data/screenshots"
  certificate_dir: "data/certificates"
  template_dir: "data/templates"
  timeout: 30  # Default timeout in seconds
  retry_attempts: 3
  delay_between_actions: 2  # Seconds between actions
  capture_video: true
  log_level: "INFO"

# AI Model Settings
ai:
  default_model: "microsoft/phi-2"  # Free model for text generation
  openrouter_models:
    - "anthropic/claude-2"
    - "google/palm-2"
  temperature: 0.7
  max_tokens: 500
  api_key: ""  # Add your OpenRouter API key here

# Browser Settings
browser:
  default: "chromium"  # chromium, firefox, or webkit
  viewport:
    width: 1920
    height: 1080
  user_agent: "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/121.0.0.0 Safari/537.36"
  headless: false  # Set to true for production

# Course Platforms
platforms:
  - name: "coursera"
    base_url: "https://www.coursera.org"
    selectors:
      login_button: "button[data-track-component='login_redirect']"
      email_input: "input[type='email']"
      password_input: "input[type='password']"
      submit_button: "button[type='submit']"
      course_progress: ".course-progress"
      video_player: ".video-player"
      play_button: ".vjs-play-control"
      pause_button: ".vjs-pause-control"
      next_button: ".next-button"
      quiz_container: ".quiz-container"
      quiz_input: "input.quiz-answer"
      quiz_submit: "button.submit-answer"
      assignment_input: "textarea.assignment-text"
      assignment_submit: "button.submit-assignment"
      
  - name: "udemy"
    base_url: "https://www.udemy.com"
    selectors:
      login_button: "a[data-purpose='header-login']"
      email_input: "#email--1"
      password_input: "#form-group--3"
      submit_button: "button[type='submit']"
      course_progress: ".curriculum-item-link--progress--23Aaf"
      video_player: ".video-player--video-wrapper--2kmnY"
      play_button: ".vjs-play-control"
      pause_button: ".vjs-pause-control"
      next_button: "[data-purpose='go-to-next']"
      quiz_container: ".mc-quiz-question--container--2MZCl"
      quiz_input: "input[type='radio']"
      quiz_submit: "button[data-purpose='submit-quiz-button']"
      assignment_input: "textarea[data-purpose='assignment-text']"
      assignment_submit: "button[data-purpose='submit-assignment']"

# Screen Monitoring
monitor:
  enabled: true
  capture_interval: 1.0  # Screen monitoring interval in seconds
  regions:
    - name: "video_player"
      coordinates: [100, 100, 1000, 700]  # [left, top, right, bottom]
    - name: "progress_bar"
      coordinates: [100, 800, 1000, 820]
    - name: "quiz_area"
      coordinates: [100, 100, 1000, 800]
    - name: "assignment_area"
      coordinates: [100, 100, 1000, 800]
  
  # Templates for image matching
  templates:
    - name: "play_button"
      path: "data/templates/play_button.png"
      confidence: 0.8
    - name: "next_button"
      path: "data/templates/next_button.png"
      confidence: 0.8
    - name: "quiz_submit"
      path: "data/templates/quiz_submit.png"
      confidence: 0.8

# Course Completion Rules
completion_rules:
  video_lectures:
    - check_play_status: true
    - minimum_watch_time: 0.9  # 90% of video length
    - check_progress_bar: true
  
  quizzes:
    - attempt_limit: 3
    - use_ai_assistance: true
    - save_answers: true
  
  assignments:
    - use_ai_assistance: true
    - plagiarism_check: true
    - review_before_submit: true

# Error Handling
error_handling:
  captcha:
    - detection_method: "image_recognition"
    - solver_service: "2captcha"  # Configure if needed
  
  network:
    - retry_count: 3
    - backoff_factor: 2
    - max_delay: 60
  
  session:
    - auto_refresh: true
    - max_session_time: 7200  # 2 hours

# Logging Configuration
logging:
  log_dir: "logs"
  max_size: 10485760  # 10MB
  backup_count: 5
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
  date_format: "%Y-%m-%d %H:%M:%S" 